// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: proto/actiongame.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnState int32

const (
	ConnState_JOIN  ConnState = 0
	ConnState_LEAVE ConnState = 1
	ConnState_SPAWN ConnState = 2
)

// Enum value maps for ConnState.
var (
	ConnState_name = map[int32]string{
		0: "JOIN",
		1: "LEAVE",
		2: "SPAWN",
	}
	ConnState_value = map[string]int32{
		"JOIN":  0,
		"LEAVE": 1,
		"SPAWN": 2,
	}
)

func (x ConnState) Enum() *ConnState {
	p := new(ConnState)
	*p = x
	return p
}

func (x ConnState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_actiongame_proto_enumTypes[0].Descriptor()
}

func (ConnState) Type() protoreflect.EnumType {
	return &file_proto_actiongame_proto_enumTypes[0]
}

func (x ConnState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnState.Descriptor instead.
func (ConnState) EnumDescriptor() ([]byte, []int) {
	return file_proto_actiongame_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actiongame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actiongame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_actiongame_proto_rawDescGZIP(), []int{0}
}

type HelloReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actiongame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actiongame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_proto_actiongame_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *HelloRes) Reset() {
	*x = HelloRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actiongame_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRes) ProtoMessage() {}

func (x *HelloRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actiongame_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRes.ProtoReflect.Descriptor instead.
func (*HelloRes) Descriptor() ([]byte, []int) {
	return file_proto_actiongame_proto_rawDescGZIP(), []int{2}
}

func (x *HelloRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetPlayerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPlayerReq) Reset() {
	*x = GetPlayerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actiongame_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerReq) ProtoMessage() {}

func (x *GetPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actiongame_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerReq.ProtoReflect.Descriptor instead.
func (*GetPlayerReq) Descriptor() ([]byte, []int) {
	return file_proto_actiongame_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPlayerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetPlayerRes) Reset() {
	*x = GetPlayerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actiongame_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRes) ProtoMessage() {}

func (x *GetPlayerRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actiongame_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRes.ProtoReflect.Descriptor instead.
func (*GetPlayerRes) Descriptor() ([]byte, []int) {
	return file_proto_actiongame_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlayerRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPlayerRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type JoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *JoinReq) Reset() {
	*x = JoinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actiongame_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReq) ProtoMessage() {}

func (x *JoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actiongame_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReq.ProtoReflect.Descriptor instead.
func (*JoinReq) Descriptor() ([]byte, []int) {
	return file_proto_actiongame_proto_rawDescGZIP(), []int{5}
}

func (x *JoinReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlayerConn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type ConnState `protobuf:"varint,2,opt,name=type,proto3,enum=proto.ConnState" json:"type,omitempty"`
}

func (x *PlayerConn) Reset() {
	*x = PlayerConn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actiongame_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerConn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerConn) ProtoMessage() {}

func (x *PlayerConn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actiongame_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerConn.ProtoReflect.Descriptor instead.
func (*PlayerConn) Descriptor() ([]byte, []int) {
	return file_proto_actiongame_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerConn) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerConn) GetType() ConnState {
	if x != nil {
		return x.Type
	}
	return ConnState_JOIN
}

type Pos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X  float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y  float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z  float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Rx float32 `protobuf:"fixed32,4,opt,name=rx,proto3" json:"rx,omitempty"`
	Ry float32 `protobuf:"fixed32,5,opt,name=ry,proto3" json:"ry,omitempty"`
	Rz float32 `protobuf:"fixed32,6,opt,name=rz,proto3" json:"rz,omitempty"`
}

func (x *Pos) Reset() {
	*x = Pos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actiongame_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actiongame_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_proto_actiongame_proto_rawDescGZIP(), []int{7}
}

func (x *Pos) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pos) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Pos) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Pos) GetRx() float32 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *Pos) GetRy() float32 {
	if x != nil {
		return x.Ry
	}
	return 0
}

func (x *Pos) GetRz() float32 {
	if x != nil {
		return x.Rz
	}
	return 0
}

type PlayerMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pos *Pos   `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *PlayerMove) Reset() {
	*x = PlayerMove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actiongame_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMove) ProtoMessage() {}

func (x *PlayerMove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actiongame_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMove.ProtoReflect.Descriptor instead.
func (*PlayerMove) Descriptor() ([]byte, []int) {
	return file_proto_actiongame_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerMove) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerMove) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

var File_proto_actiongame_proto protoreflect.FileDescriptor

var file_proto_actiongame_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1e, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1c, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1d, 0x0a, 0x07, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x42, 0x0a, 0x0a, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f,
	0x6e, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x5f, 0x0a,
	0x03, 0x50, 0x6f, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79,
	0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x0e,
	0x0a, 0x02, 0x72, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x72, 0x78, 0x12, 0x0e,
	0x0a, 0x02, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x72, 0x79, 0x12, 0x0e,
	0x0a, 0x02, 0x72, 0x7a, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x72, 0x7a, 0x22, 0x3a,
	0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x03,
	0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x2a, 0x2b, 0x0a, 0x09, 0x43, 0x6f,
	0x6e, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x4f, 0x49, 0x4e, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x50, 0x41, 0x57, 0x4e, 0x10, 0x02, 0x32, 0xc0, 0x01, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65,
	0x12, 0x29, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x30, 0x01, 0x12,
	0x29, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6f, 0x73, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x12, 0x5a, 0x10, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_actiongame_proto_rawDescOnce sync.Once
	file_proto_actiongame_proto_rawDescData = file_proto_actiongame_proto_rawDesc
)

func file_proto_actiongame_proto_rawDescGZIP() []byte {
	file_proto_actiongame_proto_rawDescOnce.Do(func() {
		file_proto_actiongame_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_actiongame_proto_rawDescData)
	})
	return file_proto_actiongame_proto_rawDescData
}

var file_proto_actiongame_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_actiongame_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_actiongame_proto_goTypes = []interface{}{
	(ConnState)(0),       // 0: proto.ConnState
	(*Empty)(nil),        // 1: proto.Empty
	(*HelloReq)(nil),     // 2: proto.HelloReq
	(*HelloRes)(nil),     // 3: proto.HelloRes
	(*GetPlayerReq)(nil), // 4: proto.GetPlayerReq
	(*GetPlayerRes)(nil), // 5: proto.GetPlayerRes
	(*JoinReq)(nil),      // 6: proto.JoinReq
	(*PlayerConn)(nil),   // 7: proto.PlayerConn
	(*Pos)(nil),          // 8: proto.Pos
	(*PlayerMove)(nil),   // 9: proto.PlayerMove
}
var file_proto_actiongame_proto_depIdxs = []int32{
	0, // 0: proto.PlayerConn.type:type_name -> proto.ConnState
	8, // 1: proto.PlayerMove.pos:type_name -> proto.Pos
	2, // 2: proto.Game.Hello:input_type -> proto.HelloReq
	4, // 3: proto.Game.GetPlayer:input_type -> proto.GetPlayerReq
	6, // 4: proto.Game.Join:input_type -> proto.JoinReq
	8, // 5: proto.Game.Move:input_type -> proto.Pos
	3, // 6: proto.Game.Hello:output_type -> proto.HelloRes
	5, // 7: proto.Game.GetPlayer:output_type -> proto.GetPlayerRes
	7, // 8: proto.Game.Join:output_type -> proto.PlayerConn
	9, // 9: proto.Game.Move:output_type -> proto.PlayerMove
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_actiongame_proto_init() }
func file_proto_actiongame_proto_init() {
	if File_proto_actiongame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_actiongame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actiongame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actiongame_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actiongame_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actiongame_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actiongame_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actiongame_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerConn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actiongame_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actiongame_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_actiongame_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_actiongame_proto_goTypes,
		DependencyIndexes: file_proto_actiongame_proto_depIdxs,
		EnumInfos:         file_proto_actiongame_proto_enumTypes,
		MessageInfos:      file_proto_actiongame_proto_msgTypes,
	}.Build()
	File_proto_actiongame_proto = out.File
	file_proto_actiongame_proto_rawDesc = nil
	file_proto_actiongame_proto_goTypes = nil
	file_proto_actiongame_proto_depIdxs = nil
}
